
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qureshi Home
 */
public class TruckPanel extends javax.swing.JFrame {

    /**
     * Creates new form TruckPannel
     */
    public TruckPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        mpg1Btn = new javax.swing.JButton();
        mpg2Btn = new javax.swing.JButton();
        l7 = new javax.swing.JLabel();
        txtMPG = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        l8 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        txt8 = new javax.swing.JTextField();
        l10 = new javax.swing.JLabel();
        txt9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        l1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Make");

        txt1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Model");

        txt2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Year");

        txt3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Doors");

        txt4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("Fuel Capacity");

        txt5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        mpg1Btn.setBackground(new java.awt.Color(51, 51, 51));
        mpg1Btn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        mpg1Btn.setForeground(new java.awt.Color(255, 153, 0));
        mpg1Btn.setText("MPG without Extra Load");
        mpg1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpg1BtnActionPerformed(evt);
            }
        });

        mpg2Btn.setBackground(new java.awt.Color(51, 51, 51));
        mpg2Btn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        mpg2Btn.setForeground(new java.awt.Color(255, 153, 0));
        mpg2Btn.setText("MPG with Extra Load");
        mpg2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpg2BtnActionPerformed(evt);
            }
        });

        l7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));
        l7.setText("MPG");

        txtMPG.setEditable(false);
        txtMPG.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setText("Driving Range");

        txt7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));
        l8.setText("Extra Load");

        Title.setFont(new java.awt.Font("Yahoo", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 153, 0));
        Title.setText("Truck DETAILS");

        l9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setText("Towing Capacity");

        txt8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setText("Payload Capacity");

        txt9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(l1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(l2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(l3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(l4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(l7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMPG, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(l8)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mpg1Btn)
                                .addGap(18, 18, 18)
                                .addComponent(mpg2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(l9)
                            .addGap(18, 18, 18)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(l6)
                                .addComponent(l5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l10)
                        .addGap(18, 18, 18)
                        .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Title)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l6)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l9)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l7)
                    .addComponent(txtMPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l8)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpg1Btn)
                    .addComponent(mpg2Btn))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpg1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpg1BtnActionPerformed
        int year = 0,doors =0,fuel =0,drivingRange =0,load = 0,towing=0,payload=0;
        try{
            year = Integer.parseInt(txt3.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Year Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            doors = Integer.parseInt(txt4.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Doors Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            fuel = Integer.parseInt(txt5.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Fuel Tank Capacity Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            drivingRange = Integer.parseInt(txt6.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Driving Range Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            load = Integer.parseInt(txt7.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Extra Load Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            towing = Integer.parseInt(txt8.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Towing Capacity Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            payload = Integer.parseInt(txt9.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Payload Capacity Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        Truck truck = new Truck(txt1.getText(),txt2.getText(),year,doors,fuel,drivingRange,towing,payload);
        txtMPG.setText(truck.calcMPG()+"");

    }//GEN-LAST:event_mpg1BtnActionPerformed

    private void mpg2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpg2BtnActionPerformed
         int year = 0,doors =0,fuel =0,drivingRange =0,load = 0,towing=0,payload=0;
        try{
            year = Integer.parseInt(txt3.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Year Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            doors = Integer.parseInt(txt4.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Doors Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            fuel = Integer.parseInt(txt5.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Fuel Tank Capacity Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            drivingRange = Integer.parseInt(txt6.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Driving Range Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            load = Integer.parseInt(txt7.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Extra Load Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            towing = Integer.parseInt(txt8.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Towing Capacity Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        try{
            payload = Integer.parseInt(txt9.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog (null, "Payload Capacity Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
        }
        Truck truck = new Truck(txt1.getText(),txt2.getText(),year,doors,fuel,drivingRange,towing,payload);
        txtMPG.setText(truck.calcMPG(load)+"");

    }//GEN-LAST:event_mpg2BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TruckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TruckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TruckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TruckPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TruckPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JButton mpg1Btn;
    private javax.swing.JButton mpg2Btn;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JTextField txtMPG;
    // End of variables declaration//GEN-END:variables
}
